name: Build and Sign Firefox Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Lint Check
        run: web-ext lint --self-hosted --source-dir ./src

      - name: Build & Sign Firefox Extension
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: web-ext sign --channel unlisted --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --source-dir ./src

      - name: Get version code
        id: version_code
        run: |
          TAG=v$(jq -r .version src/manifest.json)
          echo "VERSION=${TAG}" >> $GITHUB_OUTPUT

      - name: Relase Body
        id: body
        run: |
          DELIM="$(openssl rand -hex 8)"
          echo "BODY<<${DELIM}" >> "$GITHUB_OUTPUT"
          echo  "## Main features

            - Light/Dark Mode
            - Time-based greeting
            - Built-in search integration: (DuckDuckGO)
                - __When focused on the search bar__:
                    - Press `Enter` to search
            - Quick access to your favorite websites

            ## Changelog

            - Now Completly Local i.e fonts and icons are packed within the extension">> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"

      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Custom Startpage
          tag: ${{ steps.version_code.outputs.VERSION }}
          body: ${{ steps.body.outputs.BODY }}
          file: ./web-ext-artifacts/*.xpi
          file_glob: true
          overwrite: true

      - name: Update JSON
        run: |
            VERSION="$(jq -r .version src/manifest.json)"
            LINK="https://github.com/Tokito-to/startpage/releases/download/v${VERSION}/50fd4af065914df190c5-${VERSION}.xpi"
            HASH="$(sha256sum ./web-ext-artifacts/*.xpi | cut -d' ' -f1)"

            cp update.json ./tmp.json
            jq --arg VERSION "$VERSION" --arg LINK "$LINK" --arg HASH "sha256:$HASH" \
              '.addons |= map_values(.updates += [{"version": $VERSION, "update_link": $LINK, "update_hash": $HASH}])' ./tmp.json > ./update.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          skip_checkout: true
          file_pattern: update.json
          commit_message: "startpage: publish update"
